name: unittest
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: pipx install poetry
    - name: Show Poetry Environment Info
      run: poetry env info
    - name: Install Development Dependencies
      run: poetry install --no-root
    - name: unittest
      run: poetry run coverage run tests/test_runner.py
